name: Deploy Application

on:
  push:
    branches: [ main ]

jobs:

  deployApplication:
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build binary
        run: make build
        env:
          GOOS: linux
          GOARCH: amd64
