name: Golang Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    environment: staging
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Run unit tests
      run: make test

    - name: Build binary
      run: make build
      env:
        GOOS: linux
        GOARCH: amd64
