name: Check for TODOs

on:
  pull_request:

jobs:

  checkForTodos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Find TODOs
        shell: bash
        run: |
          if git diff origin/main HEAD --no-ext-diff --unified=0 --exit-code -a --no-prefix ':!.github/workflows/todo.yml' | egrep '^\+.*[tT][oO][dD][oO]'; \
          then echo 'OK!'; \
          else echo 'You cannot merge PRs with TODOs'; exit 1; fi
