name: Deploy Application

on:
  push:
    branches: [ main ]

jobs:

  bumpVersion:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Bump version patch number
      id: version_bump
      run: echo "::set-output name=versions::$(make patch-version | tr '\n' '|')\n"

    - name: Commit version change
      uses: EndBug/add-and-commit@v7.0.0
      with:
        message: |
          [automated] bump version

          ${{ steps.version_bump.outputs.versions }}

  # deployApplication:
  #   environment: staging
  #   needs: bumpVersion
  #   runs-on: ubuntu-latest
